package protocole;


public enum TypeMessage {
    DIFFUSION_CONNECTION,
    DIFFUSION_DEBUT_JEU,
    REPONSE_CONNECTION,
    DIFFUSION_NUMEROTATION,//Lance l'etape de numerotation
    MESSAGE_NUMEROTATION,//les joueurs envoient leur numero
    REPONSE_NUMEROTATION,//les joueurs se renvoient un ack 
    DIFFUSION_FIN_NUMEROTATION,
    DIFFUSION_EJECTION,
    MESSAGE_ELECTION,
    DIFFUSION_MAITRE,
    MESSAGE_DISTRIBUTION, 
    DIFFUSION_FIN_DISTRIBUTION,
    MESSAGE_FIN_OK_DISTRIBUTION,
    MESSAGE_ECHANGE,
    REPONSE_AU_MAITRE,
    MESSAGE_AFFICHE,
    DIFFUSION_AFFICHE,
    DIFFUSION_FIN_PARTIE
}
